### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by n-marion** [zODSP/JKG2AT#6]
**Description**
Currently there is no error checking within our script. Bugs have been hit when not enough space is provided or if an error occurs while unpackaging the .tar.gz files. We should handle errors and provide details back to user.

**Error Example**
`gunzip is gunzip
/s/SPARK/jupyter/python created
Unpackaging Python (this may take several minutes)
gunzip: /s/SPARK/jupyter/setupEcosystem.sh 200: FSUM7351 not found
CEE5213S The signal SIGPIPE was received.
0 blocks
FSUM7131 Out of space or reached the end of the archive file.
If you want to go on, type device or file name when ready`

**To Reproduce**
This particular issue occurs due to packages being transferred non-binary to z/OS system. Once you attempt to untar files, it runs into problem.

**Tasks**
- [ ] Handle if unpackaging fails. Delete the directory to allow future runs to reinstall.
- [ ] Provide explanation for errors
- [ ] Check for enough space prior to attempting first install
